import {
  BusinessIcon,
  DesignIcon,
  DevelopmentIcon,
  ItIcon,
  MarketIcon,
  PhotographyIcon,
} from "@/components/icons/Icons";

export const categories = [
  { name: "Featured", featured: false },
  { name: "Music", featured: false },
  { name: "Drawing & Painting", featured: false },
  { name: "Marketing", featured: false },
  { name: "Animation", featured: false },
  { name: "Social Media", featured: false },
  { name: "UI/UX Design", featured: false },
  { name: "Creative Marketing", featured: false },
  { name: "Digital Illustration", featured: false },
  { name: "Film & Video", featured: false },
  { name: "Crafts", featured: false },
  { name: "Freelance & Entrepreneurship", featured: false },
  { name: "Graphic Design", featured: false },
  { name: "Photography", featured: false },
  { name: "Productivity", featured: false },
  { name: "Web Development", featured: false },
  { name: "Data Science", featured: false },
  { name: "Cooking", featured: false },
];

export const courses = [
  {
    id: 1,
    image: "/images/courses/figma.jpg",
    title: "Learn Figma from Basic",
    category: "UI/UX Design",
    instructor: "purepearl studio",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    rating: 4.5,
    level: "Beginner",
    avatars: [
      "/images/avatars/1.jpg",
      "/images/avatars/2.jpg",
      "/images/avatars/3.jpg",
      "/images/avatars/4.jpg",
    ],
    students: "26+",
    price: 25,
    featured: true,
  },
  {
    id: 2,
    image: "/images/courses/digital-asset.jpg",
    title: "Build Digital Asset",
    category: "Digital Illustration",
    instructor: "purepearl studio",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    rating: 4.5,
    level: "Beginner",
    avatars: [
      "/images/avatars/1.jpg",
      "/images/avatars/2.jpg",
      "/images/avatars/3.jpg",
      "/images/avatars/4.jpg",
    ],
    students: "26+",
    price: 25,
    featured: true,
  },
  {
    id: 3,
    image: "/images/courses/big-data.jpg",
    title: "the Power of Big Data",
    category: "Data Science",
    instructor: "purepearl studio",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    rating: 4.5,
    level: "Beginner",
    avatars: [
      "/images/avatars/1.jpg",
      "/images/avatars/2.jpg",
      "/images/avatars/3.jpg",
      "/images/avatars/4.jpg",
    ],
    students: "26+",
    price: 25,
    featured: true,
  },
  {
    id: 4,
    image: "/images/courses/productivity.jpg",
    title: "Balancing Productivity and Life",
    category: "Productivity",
    instructor: "purepearl studio",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    rating: 4.5,
    level: "Beginner",
    avatars: [
      "/images/avatars/1.jpg",
      "/images/avatars/2.jpg",
      "/images/avatars/3.jpg",
      "/images/avatars/4.jpg",
    ],
    students: "26+",
    price: 25,
    featured: true,
  },
  {
    id: 5,
    image: "/images/courses/money-management.jpg",
    title: "Mastering Money Management",
    category: "Marketing",
    instructor: "purepearl studio",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    rating: 4.5,
    level: "Beginner",
    avatars: [
      "/images/avatars/1.jpg",
      "/images/avatars/2.jpg",
      "/images/avatars/3.jpg",
      "/images/avatars/4.jpg",
    ],
    students: "26+",
    price: 25,
    featured: true,
  },
  {
    id: 6,
    image: "/images/courses/startup.jpg",
    title: "From Idea to Startup Success",
    category: "Freelance & Entrepreneurship",
    instructor: "purepearl studio",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    rating: 4.5,
    level: "Beginner",
    avatars: [
      "/images/avatars/1.jpg",
      "/images/avatars/2.jpg",
      "/images/avatars/3.jpg",
      "/images/avatars/4.jpg",
    ],
    students: "26+",
    price: 25,
    featured: true,
  },
];

export const featuredCategories = [
  {
    name: "Design",
    icon: DesignIcon,
  },
  {
    name: "Development",
    icon: DevelopmentIcon,
  },
  {
    name: "IT & Software",
    icon: ItIcon,
  },
  {
    name: "Business",
    icon: BusinessIcon,
  },
  {
    name: "Marketing",
    icon: MarketIcon,
  },
  {
    name: "Photography",
    icon: PhotographyIcon,
  },
];

export const customerReviews = [
  {
    id: 1,
    name: "Sarah M.",
    role: "Enthusiastic Learner",
    avatar: "/images/avatars/2.jpg",
    review:
      "ByteSpace has transformed my approach to learning. The diverse range of courses and the quality of content provided by creators have exceeded my expectations. The platform truly fosters a sense of community and lifelong learning.",
  },
  {
    id: 2,
    name: "James L.",
    role: "Lifelong Learner",
    avatar: "/images/avatars/1.jpg",
    review:
      "I've tried several online learning platforms, and ByteSpace stands out for its vibrant community and the variety of courses available. The easy navigation and engaging content make it a go-to platform for continuous skill development.",
  },
  {
    id: 3,
    name: "Alex B.",
    role: "Inspired Creator",
    avatar: "/images/avatars/3.jpg",
    review:
      "As a creator, ByteSpace has been a game-changer for me. The Course Editor is user-friendly, and the support from the community is incredible. It's fulfilling to see my courses making a positive impact on learners globally.",
  },
];

export const animShapesData = [
  {
    src: "/images/hero-shapes/shape1.png",
    width: 300,
    height: 300,
    alt: "shape1",
    specialClass: "shape1",
  },
  {
    src: "/images/hero-shapes/shape2.png",
    width: 300,
    height: 300,
    alt: "shape2",
    specialClass: "shape2",
  },
  {
    src: "/images/hero-shapes/shape3.png",
    width: 240,
    height: 240,
    alt: "shape3",
    specialClass: "shape3",
  },
  {
    src: "/images/hero-shapes/shape4.png",
    width: 260,
    height: 260,
    alt: "shape4",
    specialClass: "shape4",
  },
  {
    src: "/images/hero-shapes/shape5.png",
    width: 150,
    height: 150,
    alt: "shape5",
    specialClass: "shape5",
  },
  {
    src: "/images/hero-shapes/shape6.png",
    width: 200,
    height: 200,
    alt: "shape6",
    specialClass: "shape6",
  },
];
